-- Collapse measure_type fan-out for season aggregates into single rows.
--
-- Before:
--   player_stats_aggregated PK = (nba_id, team_id, season_year, season_type, per_mode, measure_type)
--   team_stats_aggregated   PK = (team_id, season_year, season_type, per_mode, measure_type)
--
-- After:
--   player_stats_aggregated PK = (nba_id, team_id, season_year, season_type, per_mode)
--   team_stats_aggregated   PK = (team_id, season_year, season_type, per_mode)
--
-- Data migration strategy:
--   1) Aggregate existing rows across measure_type using MAX() per stat column.
--   2) Drop measure_type.
--   3) Reinsert one merged row per logical key.

BEGIN;

CREATE TEMP TABLE player_stats_aggregated_merged ON COMMIT DROP AS
SELECT
    nba_id,
    team_id,
    season_year,
    max(season_label) AS season_label,
    season_type,
    per_mode,
    max(games_played) AS games_played,
    max(minutes) AS minutes,
    max(fgm) AS fgm,
    max(fga) AS fga,
    max(fg_pct) AS fg_pct,
    max(fg3m) AS fg3m,
    max(fg3a) AS fg3a,
    max(fg3_pct) AS fg3_pct,
    max(fg2m) AS fg2m,
    max(fg2a) AS fg2a,
    max(fg2_pct) AS fg2_pct,
    max(ftm) AS ftm,
    max(fta) AS fta,
    max(ft_pct) AS ft_pct,
    max(oreb) AS oreb,
    max(dreb) AS dreb,
    max(reb) AS reb,
    max(ast) AS ast,
    max(stl) AS stl,
    max(blk) AS blk,
    max(tov) AS tov,
    max(pf) AS pf,
    max(pts) AS pts,
    max(plus_minus) AS plus_minus,
    max(double_doubles) AS double_doubles,
    max(triple_doubles) AS triple_doubles,
    max(off_rating) AS off_rating,
    max(def_rating) AS def_rating,
    max(net_rating) AS net_rating,
    max(ast_pct) AS ast_pct,
    max(ast_tov) AS ast_tov,
    max(ast_ratio) AS ast_ratio,
    max(oreb_pct) AS oreb_pct,
    max(dreb_pct) AS dreb_pct,
    max(reb_pct) AS reb_pct,
    max(tm_tov_pct) AS tm_tov_pct,
    max(efg_pct) AS efg_pct,
    max(ts_pct) AS ts_pct,
    max(usg_pct) AS usg_pct,
    max(pace) AS pace,
    max(pie) AS pie,
    max(poss) AS poss,
    max(fta_rate) AS fta_rate,
    max(pts_off_tov) AS pts_off_tov,
    max(pts_2nd_chance) AS pts_2nd_chance,
    max(pts_fb) AS pts_fb,
    max(pts_paint) AS pts_paint,
    max(opp_pts_off_tov) AS opp_pts_off_tov,
    max(opp_pts_2nd_chance) AS opp_pts_2nd_chance,
    max(opp_pts_fb) AS opp_pts_fb,
    max(opp_pts_paint) AS opp_pts_paint,
    max(nba_fantasy_pts) AS nba_fantasy_pts,
    min(created_at) AS created_at,
    max(updated_at) AS updated_at,
    max(fetched_at) AS fetched_at
FROM nba.player_stats_aggregated
GROUP BY nba_id, team_id, season_year, season_type, per_mode;

ALTER TABLE nba.player_stats_aggregated DROP CONSTRAINT IF EXISTS player_stats_aggregated_pkey;
ALTER TABLE nba.player_stats_aggregated DROP COLUMN IF EXISTS measure_type;
TRUNCATE TABLE nba.player_stats_aggregated;

INSERT INTO nba.player_stats_aggregated (
    nba_id,
    team_id,
    season_year,
    season_label,
    season_type,
    per_mode,
    games_played,
    minutes,
    fgm,
    fga,
    fg_pct,
    fg3m,
    fg3a,
    fg3_pct,
    fg2m,
    fg2a,
    fg2_pct,
    ftm,
    fta,
    ft_pct,
    oreb,
    dreb,
    reb,
    ast,
    stl,
    blk,
    tov,
    pf,
    pts,
    plus_minus,
    double_doubles,
    triple_doubles,
    off_rating,
    def_rating,
    net_rating,
    ast_pct,
    ast_tov,
    ast_ratio,
    oreb_pct,
    dreb_pct,
    reb_pct,
    tm_tov_pct,
    efg_pct,
    ts_pct,
    usg_pct,
    pace,
    pie,
    poss,
    fta_rate,
    pts_off_tov,
    pts_2nd_chance,
    pts_fb,
    pts_paint,
    opp_pts_off_tov,
    opp_pts_2nd_chance,
    opp_pts_fb,
    opp_pts_paint,
    nba_fantasy_pts,
    created_at,
    updated_at,
    fetched_at
)
SELECT
    nba_id,
    team_id,
    season_year,
    season_label,
    season_type,
    per_mode,
    games_played,
    minutes,
    fgm,
    fga,
    fg_pct,
    fg3m,
    fg3a,
    fg3_pct,
    fg2m,
    fg2a,
    fg2_pct,
    ftm,
    fta,
    ft_pct,
    oreb,
    dreb,
    reb,
    ast,
    stl,
    blk,
    tov,
    pf,
    pts,
    plus_minus,
    double_doubles,
    triple_doubles,
    off_rating,
    def_rating,
    net_rating,
    ast_pct,
    ast_tov,
    ast_ratio,
    oreb_pct,
    dreb_pct,
    reb_pct,
    tm_tov_pct,
    efg_pct,
    ts_pct,
    usg_pct,
    pace,
    pie,
    poss,
    fta_rate,
    pts_off_tov,
    pts_2nd_chance,
    pts_fb,
    pts_paint,
    opp_pts_off_tov,
    opp_pts_2nd_chance,
    opp_pts_fb,
    opp_pts_paint,
    nba_fantasy_pts,
    created_at,
    updated_at,
    fetched_at
FROM player_stats_aggregated_merged;

ALTER TABLE nba.player_stats_aggregated
    ADD CONSTRAINT player_stats_aggregated_pkey
    PRIMARY KEY (nba_id, team_id, season_year, season_type, per_mode);

CREATE TEMP TABLE team_stats_aggregated_merged ON COMMIT DROP AS
SELECT
    team_id,
    season_year,
    max(season_label) AS season_label,
    season_type,
    per_mode,
    max(games_played) AS games_played,
    max(wins) AS wins,
    max(losses) AS losses,
    max(win_pct) AS win_pct,
    max(minutes) AS minutes,
    max(fgm) AS fgm,
    max(fga) AS fga,
    max(fg_pct) AS fg_pct,
    max(fg3m) AS fg3m,
    max(fg3a) AS fg3a,
    max(fg3_pct) AS fg3_pct,
    max(fg2m) AS fg2m,
    max(fg2a) AS fg2a,
    max(fg2_pct) AS fg2_pct,
    max(ftm) AS ftm,
    max(fta) AS fta,
    max(ft_pct) AS ft_pct,
    max(oreb) AS oreb,
    max(dreb) AS dreb,
    max(reb) AS reb,
    max(ast) AS ast,
    max(stl) AS stl,
    max(blk) AS blk,
    max(tov) AS tov,
    max(pf) AS pf,
    max(pts) AS pts,
    max(plus_minus) AS plus_minus,
    max(off_rating) AS off_rating,
    max(def_rating) AS def_rating,
    max(net_rating) AS net_rating,
    max(ast_pct) AS ast_pct,
    max(ast_tov) AS ast_tov,
    max(ast_ratio) AS ast_ratio,
    max(oreb_pct) AS oreb_pct,
    max(dreb_pct) AS dreb_pct,
    max(reb_pct) AS reb_pct,
    max(tm_tov_pct) AS tm_tov_pct,
    max(efg_pct) AS efg_pct,
    max(ts_pct) AS ts_pct,
    max(pace) AS pace,
    max(pie) AS pie,
    max(poss) AS poss,
    max(fta_rate) AS fta_rate,
    max(pts_off_tov) AS pts_off_tov,
    max(pts_2nd_chance) AS pts_2nd_chance,
    max(pts_fb) AS pts_fb,
    max(pts_paint) AS pts_paint,
    max(opp_pts_off_tov) AS opp_pts_off_tov,
    max(opp_pts_2nd_chance) AS opp_pts_2nd_chance,
    max(opp_pts_fb) AS opp_pts_fb,
    max(opp_pts_paint) AS opp_pts_paint,
    min(created_at) AS created_at,
    max(updated_at) AS updated_at,
    max(fetched_at) AS fetched_at
FROM nba.team_stats_aggregated
GROUP BY team_id, season_year, season_type, per_mode;

ALTER TABLE nba.team_stats_aggregated DROP CONSTRAINT IF EXISTS team_stats_aggregated_pkey;
ALTER TABLE nba.team_stats_aggregated DROP COLUMN IF EXISTS measure_type;
TRUNCATE TABLE nba.team_stats_aggregated;

INSERT INTO nba.team_stats_aggregated (
    team_id,
    season_year,
    season_label,
    season_type,
    per_mode,
    games_played,
    wins,
    losses,
    win_pct,
    minutes,
    fgm,
    fga,
    fg_pct,
    fg3m,
    fg3a,
    fg3_pct,
    fg2m,
    fg2a,
    fg2_pct,
    ftm,
    fta,
    ft_pct,
    oreb,
    dreb,
    reb,
    ast,
    stl,
    blk,
    tov,
    pf,
    pts,
    plus_minus,
    off_rating,
    def_rating,
    net_rating,
    ast_pct,
    ast_tov,
    ast_ratio,
    oreb_pct,
    dreb_pct,
    reb_pct,
    tm_tov_pct,
    efg_pct,
    ts_pct,
    pace,
    pie,
    poss,
    fta_rate,
    pts_off_tov,
    pts_2nd_chance,
    pts_fb,
    pts_paint,
    opp_pts_off_tov,
    opp_pts_2nd_chance,
    opp_pts_fb,
    opp_pts_paint,
    created_at,
    updated_at,
    fetched_at
)
SELECT
    team_id,
    season_year,
    season_label,
    season_type,
    per_mode,
    games_played,
    wins,
    losses,
    win_pct,
    minutes,
    fgm,
    fga,
    fg_pct,
    fg3m,
    fg3a,
    fg3_pct,
    fg2m,
    fg2a,
    fg2_pct,
    ftm,
    fta,
    ft_pct,
    oreb,
    dreb,
    reb,
    ast,
    stl,
    blk,
    tov,
    pf,
    pts,
    plus_minus,
    off_rating,
    def_rating,
    net_rating,
    ast_pct,
    ast_tov,
    ast_ratio,
    oreb_pct,
    dreb_pct,
    reb_pct,
    tm_tov_pct,
    efg_pct,
    ts_pct,
    pace,
    pie,
    poss,
    fta_rate,
    pts_off_tov,
    pts_2nd_chance,
    pts_fb,
    pts_paint,
    opp_pts_off_tov,
    opp_pts_2nd_chance,
    opp_pts_fb,
    opp_pts_paint,
    created_at,
    updated_at,
    fetched_at
FROM team_stats_aggregated_merged;

ALTER TABLE nba.team_stats_aggregated
    ADD CONSTRAINT team_stats_aggregated_pkey
    PRIMARY KEY (team_id, season_year, season_type, per_mode);

COMMIT;
