-- Canonical migrations entrypoint.
-- Includes archived migrations in order.

\i migrations/archive/002_remove_lineage_columns.sql
\i migrations/archive/003_team_code_and_draft_picks.sql
\i migrations/archive/004_draft_pick_tables.sql
\i migrations/archive/005_add_unique_indexes_for_upserts.sql
\i migrations/archive/006_team_transactions.sql
\i migrations/archive/007_add_missing_unique_indexes.sql
\i migrations/archive/008_team_tax_summary_unique.sql
\i migrations/archive/009_nba_team_metadata.sql
\i migrations/archive/010_composite_keys_for_nested_entities.sql
\i migrations/archive/011_draft_tables_refactor.sql
\i migrations/archive/012_analyst_views.sql
\i migrations/archive/013_salary_book_warehouse.sql
\i migrations/archive/014_update_vw_y_warehouse.sql
\i migrations/archive/015_update_salary_book_refresh.sql
\i migrations/archive/016_refresh_salary_book_warehouse_fast.sql
\i migrations/archive/017_salary_book_age_and_option_normalization.sql
\i migrations/archive/018_remove_unused_two_way_daily_statuses_columns.sql
\i migrations/archive/019_team_salary_summary.sql
\i migrations/archive/020_exceptions_warehouse.sql
\i migrations/archive/021_team_salary_summary_tax_status_flags.sql
\i migrations/archive/022_team_salary_summary_tax_status_fallback.sql
\i migrations/archive/023_rename_team_salary_summary_to_team_salary_warehouse.sql
\i migrations/archive/024_dead_money_warehouse.sql
\i migrations/archive/025_cap_holds_warehouse.sql
\i migrations/archive/026_salary_book_yearly.sql
\i migrations/archive/027_tpe_trade_math.sql
\i migrations/archive/028_fix_exceptions_warehouse_team_code_and_lookups.sql
\i migrations/archive/029_trade_planner_tpe.sql
\i migrations/archive/030_trade_planner_tpe_output_totals.sql
\i migrations/archive/031_trade_planner_tpe_ui_fields.sql
\i migrations/archive/032_trade_planner_tpe_summary.sql
\i migrations/archive/033_trade_planner_tpe_summary_delta.sql
\i migrations/archive/034_salary_book_multi_contract_year_selection.sql
\i migrations/archive/035_player_rights_warehouse.sql
\i migrations/archive/036_fix_player_rights_warehouse_drlst_sender.sql
\i migrations/archive/037_player_rights_warehouse_filter_cdl.sql
\i migrations/archive/038_draft_picks_warehouses.sql
\i migrations/archive/039_draft_pick_slots_warehouse_outcomes.sql
\i migrations/archive/040_draft_pick_trade_claims_warehouse.sql
\i migrations/archive/041_draft_assets_warehouse.sql
\i migrations/archive/042_exceptions_warehouse_proration.sql
\i migrations/archive/043_salary_book_player_consent_flags.sql
\i migrations/archive/044_salary_book_yearly_player_consent_flags.sql
\i migrations/archive/045_endnotes_schema_v2.sql
\i migrations/archive/046_salary_book_is_two_way_from_contract_type.sql
\i migrations/archive/047_salary_book_is_two_way_include_regcv.sql
\i migrations/archive/048_salary_book_is_two_way_keep_multi_contract_year_selection.sql
\i migrations/archive/049_salary_book_refresh_keep_player_consent.sql
\i migrations/archive/050_salary_book_guarantees_and_bonuses.sql
\i migrations/archive/051_team_salary_warehouse_exclude_two_way_from_roster_count.sql
\i migrations/archive/052_salary_book_pct_cap_percentiles.sql
\i migrations/archive/053_salary_book_contract_type_metadata.sql
